#!/bin/bash

WHAT="$1"
MNTP="/media"

# no checks here, be careful!
TFILE="${HOME}/myshinytomb"
KFILE="${HOME}/myshinytomb.key"

SANDTOMB=`which sandtomb`
TOMBIN=`which tomb`

# check if we passed a real program to sandbox
if ! [ "${WHAT}" ] || ! [ "`which ${WHAT}`" ]; then
	exit 1
fi

"${TOMB}" list "`basename ${TFILE}`" &> /dev/null

if [ $? -eq 1 ]; then
	"${TOMBIN}" open "${TFILE}"
fi

if [ $? -eq 1 ]; then
	exit 1
fi

TOMBMOUNT="${MNTP}/"`basename ${TFILE}`""

sudo "${SANDTOMB}" --mountpoint "${TOMBMOUNT}" --profile "${WHAT}" "${WHAT}"
