#!/bin/bash

WHAT="$1"
MNTP="/media"

TFILE="${HOME}/myshinytomb"
KFILE="${HOME}/myshinytomb.key"
BIN="${PWD}/bin"
SANDTOMB="${BIN}/sandtomb"
TOMBIN="${BIN}/tomb"
SUDO="`which sudo`"

function usage() {
	echo "Usage:"
	echo "$0 <program | info>"
	echo "program: program to sandbox into tomb"
	echo "info: print sandstart informations"
}

function check_bin() {
	if ! [ -e "${1}" ]; then
		return 1
	fi
	return 0
}

function print_info() {
	local notfound

	echo "sandstart info:"
	echo "Tomb file path: $TFILE"
	echo "Tomb keyfile: $KFILE"
	echo "Tomb mount point: $MNTP"
	check_bin "${TOMBIN}"
	if [ "$?" -eq 1 ]; then
		notfound="[NOT FOUND]"
	fi
	echo "Tomb binary path: $TOMBIN $notfound"
	check_bin "${SANDTOMB}"
	if [ "$?" -eq 1 ]; then
		notfound="[NOT FOUND]"
	fi
	echo "Sandtomb path: $SANDTOMB $notfound"
}

# check if we passed a real program to sandbox
if  [ "$#" -lt 1 ]; then
	usage
	exit 1
fi

if [ "${WHAT}" == "info" ]; then
	print_info
	exit 0
elif ! [ "`which ${WHAT}`" ]; then
	echo "Error: cannot find $WHAT"
	exit 1
fi

check_bin "${TOMBIN}"
if [ "$?" -eq 1 ]; then
	echo "Error: tomb not found. Please run '$0 info' for more informations"
	exit 1
fi

check_bin "${SANDTOMB}"
if [ "$?" -eq 1 ]; then
	echo "Error: sandtomb not found. Please run '$0 info' for more informations"
	exit 1
fi

if ! [ "${SUDO}" ] || ! [ -e "${SUDO}" ]; then
	echo "Error: 'sudo' not found. Please install it."
	exit 1
fi

# check if tomb file or tomb key exists
if ! [ -e "${TFILE}" ] || ! [ -e "${KFILE}" ]; then
	echo "Error: cannot find $TFILE or $KFILE. Please run '$0 info' for more informations"
	exit 1
fi

# check if we have the tomb already opened
"${TOMBIN}" list "`basename ${TFILE}`" &>/dev/null
if [ "$?" -eq 1 ]; then
	# if not, open it
	"${TOMBIN}" open "${TFILE}" -k "${KFILE}"
	if [ "$?" -eq 1 ]; then
		exit 1
	fi
fi

TOMBMOUNT="${MNTP}/"`basename ${TFILE}`""
"${SUDO}" "${SANDTOMB}" --mountpoint "${TOMBMOUNT}" --profile "${WHAT}" "${WHAT}"
